### PR TITLE
Source local secrets file, if exists

### PR DESCRIPTION
**Pull request by victor-nitu**
I keep thinking we need a local file sourced into the main secrets file.
Here's a rough implementation.

Thoughts? Improvements? Comments?

### CODE REVIEW

**Comment by akariv** [comment]
Have you tested this?

**Comment by akariv** [comment]
@nightsh

**Comment by victor-nitu** [comment]
@akariv I tested it in an isolated context, i.e. shell script that conditionally sources another script and actually exports the new values to env. If you do this it works:

```bash
source ./ckan-secrets.sh
echo $CKAN_SITE_URL
```

I can't do an end to end test yet, as my local docker-compose stopped working and I didn't have time to fix it. I can do it tomorrow, likely, but maybe someone else wants to try it until then so I won't block the process.

**Comment by victor-nitu** [comment]
@akariv I managed to fix my local env, tested, found the (rather obvious) issue and fixed it. Now it works and it's awaiting review.

P.S. Still needs the docs to be amended.

**Review by akariv — CHANGES_REQUESTED** [review]
Please add to this PR a detailed explanation of the use-case and why this is needed (I'm not convinced yet but maybe you can change my mine)

Also:
- Please make sure only relevant commits are present
- Commit messages explain what had been done (e.g. not 'update docker-compose.yaml' :( )
- don't rename files if not crucial (i.e. keep it 'secrets-centralized.sh' and not 'ckan-secrets-centralized.sh'

**Comment by victor-nitu** [comment]
* this will end in a squash merge, if not squashed manually before that - there will only be one commit once we agree on the implementation
* I will definitely document the use case, but the main idea is to be able to gitgnore local secrets file instead of carrying a master `ckan-secrets.sh` file across local deployments and modifying a VCS-tracked resource
* I've only renamed the files **inside** the containers, in the source tree they just moved into a `secrets/` directory that gets mounted with all its contents (so file names should be the same as in source tree, meaning that we _have_ to rename them in either of the two places, as they were copied under a different name in the image)

**Comment by akariv** [comment]
1. There are commits with unrelated changes here.
2. Please add the use case documentation to the PR 
3. Why do we need the non local version of the secrets file now? Why not remove it from git altogether?

**Comment by victor-nitu** [comment]
1. Agreed, I'm not sure how they ended up here, but that's fixable.
2. Today, sure.
3. So we can provide defaults in a centralized location. Same model `docker-compose` has about YAML overrides, just with shell-exported things.

**Comment by akariv** [comment]
Defaults for secrets in a public repo?
This file is currently a template to be filled by users - so we can either
change it to be a template or keep the template in the readme.

**Comment by ciolansteen** [comment]
tested this and everything works. I need to know if we will: 
  1) Keep the old template of which contents are already documented 
  2) Use the new local one ignored by git

**Pull request closed without merging**
