### PR TITLE
Bind to localhost everything but proxy

### PR DESCRIPTION
**Pull request by victor-nitu**
I haven't tested this thoroughly yet, but it seems like we have a security flaw in our design that needs fixing. Needs more testing and review so it won't break anything.

### CODE REVIEW

**Review by akariv — CHANGES_REQUESTED** [review]
Why bind to localhost? These ports should not be exposed at all.

**Comment by victor-nitu** [comment]
@akariv sorry I got confused (and scared in my misunderstanding) by the listing of docker ports:

```
PORTS                                      
80/tcp, 0.0.0.0:8080->8080/tcp             
0.0.0.0:8081->80/tcp                       
0.0.0.0:5000->5000/tcp                     
0.0.0.0:5432->5432/tcp                     
0.0.0.0:5433->5432/tcp                     
0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   
0.0.0.0:8983->8983/tcp                     
0.0.0.0:6379->6379/tcp                     
8000/tcp, 0.0.0.0:8800->8800/tcp           
0.0.0.0:5434->5432/tcp                     
```

And by what `netstat` was saying at the same time:

```
tcp6       0      0 :::8080                 :::*                    LISTEN      12681/docker-proxy  
tcp6       0      0 :::80                   :::*                    LISTEN      11494/docker-proxy  
tcp6       0      0 :::8081                 :::*                    LISTEN      12548/docker-proxy  
tcp6       0      0 :::22                   :::*                    LISTEN      16615/sshd          
tcp6       0      0 :::8983                 :::*                    LISTEN      11420/docker-proxy  
tcp6       0      0 :::5432                 :::*                    LISTEN      11571/docker-proxy  
tcp6       0      0 :::5433                 :::*                    LISTEN      11612/docker-proxy  
tcp6       0      0 :::5434                 :::*                    LISTEN      11245/docker-proxy  
tcp6       0      0 :::443                  :::*                    LISTEN      11464/docker-proxy  
tcp6       0      0 :::8800                 :::*                    LISTEN      11275/docker-proxy  
tcp6       0      0 :::5000                 :::*                    LISTEN      12309/docker-proxy  
tcp6       0      0 :::6379                 :::*                    LISTEN      11349/docker-proxy
```

So I sent a super rough PR for review and amend by the people doing the deployments. I did not conduct a proper investigation, but figured it'd e easier to express my thoughts in a diff than by chat messages.

Also sorry for the n00b mistake of misreading the docker port bind syntax. Happens every now and then...

Now I see the "problem" relates more to IPv6. I have not much experience running v6 networks, but feel free to close this if you find it irrelevant, which might very well be.

**Comment by akariv** [comment]
Not sure I follow... Ports should not be open unless 80/443

IPv4 or v6 is not related to this issue in any way

**Comment by akariv** [comment]
In short, don't use 'ports' when you don't want to expose ports, use 'expose' instead.

**Comment by victor-nitu** [comment]
@akariv can we wrap this up and close it, as it doesn't go anywhere? There's an [issue](https://github.com/datopian/support/issues/56) now to deal with -compose environments and I expect new PRs will follow that have nothing to do with this diff here.

**Comment by akariv** [comment]
No @nightsh, let's please implement the solution specified in my last comment.

**Pull request closed without merging**
