### PR TITLE
Vital strategies deployment

### PR DESCRIPTION
**Pull request by victor-nitu**
Summary:

- extracted DB layer
- added traefik with letsencrypt
- added VS theme / template / configuration
- replaced s3filestore with cloudstorage
- add Varnish

### CODE REVIEW

**Review by OriHoch — APPROVED** [review]
looks good :+1:

**Review by OriHoch — APPROVED** [review]
looks good, just a couple of issues which you can fix after merge:

1. Fix the build - not directly related to your PR I think, but as you are the last one who developed it so it's best if you fix it :)  It's due to Debian version our ckan image is based on which was removed from the debian mirrors. ~I think best solution is to update to LTS, see - https://wiki.debian.org/LTS/Using~
2. add some documentation like an architecture overview and some usage notes for the new components / features

**Comment by OriHoch** [comment]
Regarding Debian - I see we are already using the right deb source..

**Comment by victor-nitu** [comment]
Re: Debian - it happened to me in the past that Travis itself had limited connectivity for a short time, then everything went back to normal. I can't tell if this is the case here as well yet.

I am writing the missing documentation right now, no worries :) - I'd like to push it before merge, so I won't forget.
*(maybe when I push it, Travis will know how to reach the repos?)*

**Comment by OriHoch** [comment]
I think it's a real problem, jessie-updates seems to have been removed from the mirrors

it should happen when building locally as well

**Pull request merged**
